version: "3.2"
services:

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass 2wp-api-password
    ports:
      - "6379:6379"
    volumes:
      - $PWD/data/redis-data:/var/lib/redis
      - $PWD/data/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
